// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXn0bYuGouEM_Nt8a-p78-7yqiBI7JrrU',
    appId: '1:210538946120:web:b379655617df6a39b1427d',
    messagingSenderId: '210538946120',
    projectId: 'example-menu-1',
    authDomain: 'example-menu-1.firebaseapp.com',
    storageBucket: 'example-menu-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSq-4PZmN2MOwCt2ETd-V0YM0M1dDf6Wg',
    appId: '1:210538946120:android:c9530a731bb33ed8b1427d',
    messagingSenderId: '210538946120',
    projectId: 'example-menu-1',
    storageBucket: 'example-menu-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDQOG0H_zs-pU-monhHn2NrX847xIDxeA',
    appId: '1:210538946120:ios:451bc3b103db70abb1427d',
    messagingSenderId: '210538946120',
    projectId: 'example-menu-1',
    storageBucket: 'example-menu-1.appspot.com',
    iosBundleId: 'com.example.exampleMenu',
  );
}
